### ISSUE TITLE
How to update Scoped Models without re-fetching API

### ISSUE THREAD

**Issue by HugoKempfer** [MeshackMusundi/flutter_mvvm_example#2]
Hi,
I really like the way you implemented the MVVM pattern taking advantage of both Future builders and scoped models. 

I also read your blog's article and I tried to implement your architecture by myself.
As you did I can set a pretty neat descending data flow from the View Models to the sub-widgets through the Future Builders.

Thus far, I had no problems, but I wonder how I can update the data locally without re-fetching the API.
Because all data are stored in View Models under the Future<> class, is that even possible to work with data that isn't "read-only"?

Maybe I'm wrong in my way to think it? But I wanted your feedback on that.
How would you deal with it?
![mvvm](https://user-images.githubusercontent.com/16415225/55557163-888fb980-56e9-11e9-8dc1-0e8201436d19.png)

**Comment by MeshackMusundi** [comment]
Hi, that's an interesting question. If say you have a `name` property in your view-model, which you initially set by making an api call, you can update that property by calling a method in the view-model that makes the necessary update.
```dart
Future<String> _name;
Future<String> get name => _name;
set name(Future<String> value) {
    _name = value;
    notifyListeners();
}

...

String updateName(String newName) {
   name = Future.value(newName);
   return newName;
}
```
Then in your view you might do something like this,
```dart
FlatButton(
   child: Text('Update Name'),
   onPressed: () => model.updateName('John Doe');
)
```

**Comment by HugoKempfer** [comment]
Hi, I'm sorry for my answer late! I reworked the architecture including your solution, and it fits well :)
Thank again!
